// cadflairreactapp/src/pages/Products.tsx
import { Image, Text, Group, Grid, Paper, Stack, Title, Table, Loader, Anchor, Drawer, MultiSelect } from '@mantine/core';
import { useParams } from 'react-router-dom';
import Subscription from '../interfaces/Subscription.interface';
import ProductDefinition from '../interfaces/ProductDefinition.interface';
import useSWR from 'swr';
import { useEffect, useState } from 'react';
import Row from '../interfaces/Row.interface';

const fetcher = (url: string) => fetch(url).then(res => {
    console.log(res);
    return res.json();
})


export default function Products() {
    const params = useParams();

    const { data: subscription } = useSWR<Subscription>(`/api/v1/subscriptions/${params.companyName}`, fetcher)
    const { data: productDefinition, isLoading } = useSWR<ProductDefinition>(subscription ? `/api/v1/subscriptions/${subscription.id}/product-definitions/${params.productDefinitionName}` : null, fetcher)

    const [filteredRows, setFilteredRows] = useState<Row[]>([]);
    const columnFilters: Map<number, string[]> = new Map();

    useEffect(() => {
        setFilteredRows(productDefinition ? productDefinition.productTable.rows : []);
    }, [productDefinition]);


    if (isLoading)
        return (
            <>
                <Stack h="100%" mih="90dvh" justify="center" align="center">
                    <Loader color="blue" />
                    <Text>Loading...</Text>
                </Stack>
            </>
        );

    function getDistinctColumnValues(columnId: number): string[] {

        if (!productDefinition?.productTable?.rows)
            return [];

        const values = productDefinition.productTable.rows.map(r => r.tableValues.find(i => i.columnId === columnId)!.value)

        // Set function returns only unique values
        return [...new Set(values)]
    }

    function handleFilterChange(columnId: number, values: string[]) {
        // clear previous filter values
        columnFilters.delete(columnId);

        // set new filter values
        if (values.length > 0)
            columnFilters.set(columnId, values);

        console.log(columnFilters);

        const filteredRows = productDefinition?.productTable.rows.filter((row) => {
            for (const tableValue of row.tableValues) { 
                const columnFilter = columnFilters.get(tableValue.columnId);

                if (!columnFilter)
                    continue;

                //if (row.partNumber === "ANSI-B300-0.5B") {
                //    console.log(`filter:`);
                //    console.log(columnFilter);
                //    console.log(`table Value:`);
                //    console.log(tableValue.value);
                //}

                // check to see if this value is selected in the column filters
                if (!columnFilter.includes(tableValue.value))
                    return false;
            }

            return true;
        });

        console.log(filteredRows);
        setFilteredRows(filteredRows ? filteredRows : []);
    }


    return (
        <>
            <Grid>
                <Grid.Col span={2}>
                    <Title order={4}>Filter</Title>
                    <Stack>
                        {productDefinition?.productTable?.columns.map(col =>
                            <MultiSelect
                                key={col.id}
                                label={col.header}
                                placeholder="Pick value"
                                data={getDistinctColumnValues(col.id)}
                                onChange={(values) => handleFilterChange(col.id, values)}
                            />
                        )}
                    </Stack>
                </Grid.Col>
                <Grid.Col span={10}>
                    <h1>Product Definitions Page</h1>
                    <Title order={1}>{subscription?.companyName}</Title>

                    <Group>
                        <Image
                            src={productDefinition?.thumbnailUri}
                            height={130}
                            width={75}
                            alt="thumbnail"
                        />
                        <Stack>
                            <Text fw={500}>{productDefinition?.name}</Text>
                            <Text size="sm" c="dimmed">{productDefinition?.description}</Text>
                        </Stack>
                    </Group>

                    <Table>
                        <Table.Thead>
                            <Table.Tr>
                                <Table.Th>Part Number</Table.Th>
                                {productDefinition?.productTable?.columns.map(col =>
                                    <Table.Th key={col.id}>{col.header}</Table.Th>
                                )}
                            </Table.Tr>
                        </Table.Thead>
                        <Table.Tbody>
                            {filteredRows.map(row =>
                                <Table.Tr key={row.id}>
                                    <Table.Td>
                                        <Anchor href={`/${params.companyName}/products/${params.productDefinitionName}/${row.partNumber}`}>{row.partNumber}</Anchor>
                                    </Table.Td>
                                    {row.tableValues.map(tableValue =>
                                        <Table.Td key={tableValue.id}>{tableValue.value}</Table.Td>
                                    )}
                                </Table.Tr>
                            )}
                        </Table.Tbody>
                    </Table>
                </Grid.Col>
            </Grid>
        </>
    );

}

// CadflairAngularApp/src/app/pages/products/products.component.ts
import { CommonModule } from '@angular/common';
import { Component, Input, OnChanges, SimpleChanges, inject } from '@angular/core';
import { CatalogService } from '../../services/catalog.service';
import { Router } from '@angular/router';
import { TableModule } from 'primeng/table';
import { MultiSelectModule } from 'primeng/multiselect';
import { ButtonModule } from 'primeng/button';
import Subscription from '../../../interfaces/Subscription.interface';
import ProductDefinition from '../../../interfaces/ProductDefinition.interface';
import Row from '../../../interfaces/Row.interface';
import TableValue from '../../../interfaces/TableValue.interface';

@Component({
  selector: 'app-products',
  standalone: true,
  imports: [
    TableModule,
    CommonModule,
    MultiSelectModule,
    ButtonModule
  ],
  templateUrl: './products.component.html',
  styleUrl: './products.component.css'
})
export class ProductsComponent implements OnChanges {
  // inputs
  @Input() companyName!: string;
  @Input() productDefinitionName!: string;

  // services
  private catalogService: CatalogService = inject(CatalogService);
  private router: Router = inject(Router);

  // props
  subscription?: Subscription;
  productDefinition?: ProductDefinition;
  columnFilters: Map<number, string[]> = new Map<number, string[]>();
  filteredRows: Row[] = [];

  async ngOnChanges(changes: SimpleChanges): Promise<void> {
    this.subscription = await this.catalogService.getSubscriptionByCompanyName(this.companyName);

    if (!this.subscription)
      return;

    this.productDefinition = await this.catalogService.getProductDefinitionsBySubscriptionIdAndProductDefinitionName(this.subscription.id, this.productDefinitionName);
    this.filteredRows = this.productDefinition?.productTable.rows ?? [];
  }

  getDistinctColumnValues(columnId: number): string[] {
    if (!this.productDefinition)
      return [];

    const values = this.productDefinition.productTable.rows.map(r => r.tableValues.find(i => i.columnId === columnId)!.value)

    // Set function returns only unique values
    return [...new Set(values)]
  }

  getColumnHeader(tableValue: TableValue): string {
    return this.productDefinition?.productTable?.columns.find(c => c.id === tableValue.columnId)?.header ?? ''
  }


  onFilterChange(columnId: number, values: string[]): void {
    // clear previous filter values
    this.columnFilters.delete(columnId);

    // set new filter values
    if (values.length > 0)
      this.columnFilters.set(columnId, values);

    if (!this.productDefinition)
      return;

    const filteredRows = this.productDefinition.productTable.rows.filter((row) => {
      for (const tableValue of row.tableValues) {
        const columnFilter = this.columnFilters.get(tableValue.columnId);

        if (!columnFilter)
          continue;

        // check to see if this value is selected in the column filters
        if (!columnFilter.includes(tableValue.value))
          return false;
      }

      return true;
    });

    this.filteredRows = filteredRows;
  }

  onRowClick(partNumber: string) {
    this.router.navigate([this.subscription!.companyName, 'products', this.productDefinition!.name, partNumber ]);
  }


}

<div class="flex flex-row surface-section">
    <div style="min-width:300px;" class="p-3">
        <div class="flex flex-row justify-content-between align-items-baseline">
            <h3>Filter By</h3>
            <p>Counts: {{ filteredRows.length }}</p>
        </div>
        <div *ngIf="productDefinition" class="flex flex-column gap-3">
            <p-multiSelect *ngFor="let column of productDefinition.productTable.columns;"
                           [options]="getDistinctColumnValues(column.id)"
                           [placeholder]="column.header"
                           (onChange)="onFilterChange(column.id, $event.value)"
                           display="chip"
                           [style]="{'width':'100%'}"
                           [showClear]="true"></p-multiSelect>
        </div>
    </div>
    <div class="container container-maxwidth-lg">
        <div class="py-5">
            <h1>{{ productDefinition?.name }}</h1>
            <div class="flex flex-row gap-3">
                <div class="h-full">
                    <img [src]="productDefinition?.thumbnailUri" alt="thumbnail" class="max-h-full max-w-full" />
                </div>
                <p>{{ productDefinition?.description }}</p>
            </div>
        </div>
        <p-table *ngIf="productDefinition"
                 [value]="filteredRows"
                 responsiveLayout="stack"
                 [scrollable]="true"
                 scrollHeight="75vh"
                 [virtualScroll]="true"
                 [virtualScrollItemSize]="65">
            <ng-template pTemplate="header">
                <tr>
                    <th>Part Number</th>
                    <th *ngFor="let column of productDefinition.productTable.columns;">
                        {{ column.header }}
                    </th>
                </tr>
            </ng-template>
            <ng-template pTemplate="body" let-row>
                <tr style="height:65px">
                    <td>
                        <span class="p-column-title font-medium">Part Number</span>
                        <p-button [label]="row.partNumber" [link]="true" (onClick)="onRowClick(row.partNumber)"></p-button>
                    </td>
                    <td *ngFor="let tableValue of row.tableValues;"
                        class="p-column-title">
                        <span class="p-column-title font-medium">{{ getColumnHeader(tableValue) }}</span>{{ tableValue.value }}
                    </td>
                </tr>
            </ng-template>
        </p-table>
    </div>
</div>
